### ISSUE TITLE
npm start error. 

### ISSUE THREAD

**Issue by tyroneLord** [intrepion/react-fundamentals#1]
i am following the tutorial but i get an error when trying to use npm start. 

npm start

> react-fundamentals@1.0.0 start /Users/tgaylord/egghead_io
> webpack-dev-server

/Users/tgaylord/egghead_io/webpack.config.js:20
        ]
        ^

SyntaxError: Unexpected token ]
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! react-fundamentals@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-fundamentals@1.0.0 start script 'webpack-dev-server'.
npm ERR! This is most likely a problem with the react-fundamentals package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-fundamentals
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-fundamentals
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tgaylord/egghead_io/npm-debug.log

**Comment by intrepion** [comment]
Hello.  The very top of your error says there is a SyntaxError.

> /Users/tgaylord/egghead_io/webpack.config.js:20
> ]
> ^
> 
> SyntaxError: Unexpected token ]

It seems like you either have an extra closing bracket or something else is missing a closing brace or bracket.  You should probably double check any changes you made to the webpack.config.js file or you can post your whole file here if you want me to look at it.
